version: '3'

services:
 web:
  build: .
  volumes:
   - ./static:/code/staticfiles
  expose:
   - 8000

 nginx:
  build: ./nginx
  restart: always
  volumes:
   - ./static:/code/staticfiles
   - ./media:/code/mediafiles
  ports:
   - 8080:80
  depends_on:
   - web
