# Generated by Django 4.0.4 on 2022-04-28 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0002_author_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
    ]
