# Generated by Django 4.0.4 on 2022-04-28 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0003_remove_book_date_remove_book_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['surname']},
        ),
    ]
