# Generated by Django 4.0.4 on 2022-04-28 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0004_alter_author_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['genre']},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['language']},
        ),
    ]
