# Generated by Django 4.0.4 on 2022-05-03 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0007_buy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='book',
        ),
        migrations.AddField(
            model_name='buy',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookstore_app.book'),
        ),
    ]
