# Generated by Django 4.0.4 on 2022-05-07 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0010_alter_rent_date_return_alter_rent_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='date_return',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 12, 12, 57, 242414)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 7, 12, 12, 57, 242383)),
        ),
    ]
