# Generated by Django 4.0.4 on 2022-05-07 09:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0011_alter_rent_date_return_alter_rent_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='date_return',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 9, 15, 15, 868741, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 7, 9, 15, 15, 868702, tzinfo=utc)),
        ),
    ]
