# Generated by Django 4.0.4 on 2022-05-07 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0013_alter_rent_date_return_alter_rent_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='date_return',
            field=models.DateField(default=datetime.date(2022, 5, 21)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='date_start',
            field=models.DateField(default=datetime.date(2022, 5, 7)),
        ),
    ]
