# Generated by Django 4.0.4 on 2022-05-14 19:21

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0015_alter_book_count_alter_book_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookstore_app.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='count',
            field=models.IntegerField(default=10, error_messages={'key': 'message'}, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='bookstore_app.genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookstore_app.language', verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=50, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='date_return',
            field=models.DateField(default=datetime.date(2022, 5, 28)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='date_start',
            field=models.DateField(default=datetime.date(2022, 5, 14)),
        ),
    ]
