# Generated by Django 4.0.4 on 2022-05-14 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0016_alter_book_author_alter_book_count_alter_book_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='count',
            field=models.IntegerField(default=10, error_messages={'validators': 'Значение некорректно'}, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество'),
        ),
    ]
