# Generated by Django 4.0.4 on 2022-06-01 18:36

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookstore_app', '0017_alter_book_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='count',
            field=models.IntegerField(default=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='date_return',
            field=models.DateField(default=datetime.date(2022, 6, 15)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='date_start',
            field=models.DateField(default=datetime.date(2022, 6, 1)),
        ),
        migrations.CreateModel(
            name='UserMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Баланс')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
