# Generated by Django 4.0.4 on 2022-06-01 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0018_alter_book_count_alter_rent_date_return_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermoney',
            name='money',
            field=models.IntegerField(default=100, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Баланс'),
        ),
    ]
