# Generated by Django 4.0.4 on 2022-06-01 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0019_alter_usermoney_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermoney',
            name='money',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Баланс'),
        ),
    ]
