# Generated by Django 4.0.4 on 2022-06-04 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0020_alter_usermoney_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='rent',
            name='date_return',
            field=models.DateField(default=datetime.date(2022, 6, 18)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='date_start',
            field=models.DateField(default=datetime.date(2022, 6, 4)),
        ),
    ]
