# Generated by Django 4.0.4 on 2022-06-05 12:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0023_alter_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookstore_app.genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='date_return',
            field=models.DateField(default=datetime.date(2022, 6, 19)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='date_start',
            field=models.DateField(default=datetime.date(2022, 6, 5)),
        ),
    ]
