# Generated by Django 4.0.4 on 2022-06-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0024_remove_book_genre_book_genre_alter_book_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='bookstore_app.genre', verbose_name='Жанр'),
        ),
    ]
