# Generated by Django 4.0.4 on 2022-06-10 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0027_remove_author_country_alter_author_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Дата рождения'),
        ),
    ]
