# Generated by Django 4.0.4 on 2022-06-10 23:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0029_alter_author_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(blank=True, default='1900-01-01', verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(models.DateField(blank=True, default='1900-01-01', verbose_name='Дата рождения'))], verbose_name='Дата смерти'),
        ),
    ]
