# Generated by Django 4.0.4 on 2022-06-15 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0032_alter_book_count_alter_book_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('ENG', 'Английский'), ('DEU', 'Немецкий'), ('FRA', 'Французский'), ('RUS', 'Русский'), ('ITA', 'Итальянский'), ('SPA', 'Испанский')], max_length=3, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='date_return',
            field=models.DateField(default=datetime.date(2022, 6, 29)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='date_start',
            field=models.DateField(default=datetime.date(2022, 6, 15)),
        ),
    ]
