# Generated by Django 4.0.4 on 2022-06-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0033_alter_book_language_alter_rent_date_return_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Basnya', 'Басня'), ('Povest', 'Повесть'), ('Poema', 'Поэма'), ('Proza', 'Проза'), ('Pyesa', 'Пьеса'), ('Rasskaz', 'Рассказ'), ('Roman', 'Роман'), ('Skazka', 'Сказка'), ('Stix', 'Стихотворение')], default='Proza', max_length=20, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('ENG', 'Английский'), ('SPA', 'Испанский'), ('ITA', 'Итальянский'), ('CHI', 'Китайский'), ('DEU', 'Немецкий'), ('RUS', 'Русский'), ('FRA', 'Французский')], max_length=3, verbose_name='Язык'),
        ),
    ]
