# Generated by Django 4.0.4 on 2022-06-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0035_alter_book_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[(None, '---------'), ('Basnya', 'Басня'), ('Povest', 'Повесть'), ('Poema', 'Поэма'), ('Proza', 'Проза'), ('Pyesa', 'Пьеса'), ('Rasskaz', 'Рассказ'), ('Roman', 'Роман'), ('Skazka', 'Сказка'), ('Stix', 'Стихотворение')], max_length=20, verbose_name='Жанр'),
        ),
    ]
